[package]
name = "galeforce"
version = "0.9.27-13.0.1"
authors = ["Dyad/"]
edition = "2018"

[package.metadata.skyline]
titleid = "01006A800016E000"
plugin-dependencies = [
    { name = "libnro_hook.nro", url = "https://github.com/ultimate-research/nro-hook-plugin/releases/download/master/libnro_hook.nro" },
    { name = "libsmashline_hook.nro", url = "https://github.com/blu-dev/smashline_hook/releases/download/1.1.1/libsmashline_hook.nro" },
]

[lib]
crate-type = ["cdylib"]

[dependencies]
skyline = { git = "https://github.com/ultimate-research/skyline-rs.git" }
skyline_smash = { path = "D:/Documents/GitHub/skyline-smash-blu", features = ["weak_l2cvalue"] }
smashline = { path = "D:/Documents/GitHub/smashline"}
smash_script = { path = "D:/Documents/GitHub/smash-script"}

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true